name: Delete old workflow runs

on:
  # Chạy mỗi Chủ nhật lúc 02:37 UTC (09:37 GMT+7)
  schedule:
    - cron: '37 2 * * 0'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
