name: Xuất Playlist IPTV-ORG-RAW

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  export-playlist-virtual:
    runs-on: ubuntu-latest

    steps:
      # 1. Tải repo engine chứa mã nguồn
      - name: Checkout repo engine
        uses: actions/checkout@v4
        with:
          repository: zaltvvn/engine
          path: engine
          token: ${{ secrets.ENGINE_TOKEN }}

      # 2. Cài đặt Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Phục hồi và lưu trữ Cache JSON (BƯỚC THÊM MỚI)
      - name: Cache JSON logos
        uses: actions/cache@v4
        with:
          path: |
            github_logos.json
            iptv_logos.json
          # Tạo key mới cho mỗi lần chạy để luôn cập nhật cache mới nhất
          key: logos-json-${{ github.run_id }}
          # Phục hồi cache từ lần chạy gần nhất có prefix này
          restore-keys: |
            logos-json-

      # 4. Chạy script
      - name: Chạy Script xử lý M3U
        run: |
          pip install aiohttp requests
          python engine/playlist_iptv_orgv1.py

      # 5. Tạo nhánh ảo 'playlist' và Force Push sang zaltvvn/live
      - name: Deploy lên nhánh ảo playlist
        run: |
          # Tạo thư mục rỗng làm kho lưu trữ ảo
          mkdir temp_deploy
          
          # Đưa file m3u vừa tạo vào temp_deploy
          cp index.m3u temp_deploy/index.m3u
          
          cd temp_deploy
          
          # Khởi tạo nhánh ảo với tên mới là 'iptv-org-raw'
          git init -b iptv-org-raw
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Commit file
          git add index.m3u
          git commit -m "🔄 Tự động cập nhật playlist mới nhất"
          
          # Ghi đè sang repo zaltvvn/live vào nhánh iptv-org-raw
          git remote add origin https://${{ secrets.ENGINE_TOKEN }}@github.com/zaltvvn/live.git
          git push origin iptv-org-raw --force
